apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tochi-legal-suite
  namespace: tochi-legal-suite
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tochi.example.com
      secretName: tochi-legal-suite-tls
  rules:
    - host: tochi.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tochi-legal-suite
                port:
                  number: 80
