// Dashboard Stats
export interface DashboardStats {
  casosActivos: number;
  citasHoy: number;
  clientesTotal: number;
  documentosPendientes: number;
  ingresosMes: number;
  casosNuevosMes: number;
}

// Legal Codes Data
export interface CodigoLegalData {
  codigo: string;
  nombre: string;
  nombreCorto: string;
  urlOficial: string;
  urlSenado: string;
  urlSUIN: string;
  tipo: "constitucion" | "codigo" | "ley";
  entidadEmisora: string;
  numeroNorma: string;
  areasDelDerecho: string[];
}

export const CODIGOS_COLOMBIANOS: CodigoLegalData[] = [
  // ==================== CONSTITUCION ====================
  {
    codigo: "CONSTITUCION_1991",
    nombre: "Constitucion Politica de Colombia",
    nombreCorto: "CN",
    urlOficial: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1687988",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/constitucion_politica_1991.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1687988",
    tipo: "constitucion",
    entidadEmisora: "Asamblea Nacional Constituyente",
    numeroNorma: "Constitucion 1991",
    areasDelDerecho: ["Derecho Constitucional", "Derechos Fundamentales"],
  },

  // ==================== CODIGOS CIVILES Y COMERCIALES ====================
  {
    codigo: "CODIGO_CIVIL",
    nombre: "Codigo Civil Colombiano",
    nombreCorto: "CC",
    urlOficial: "http://leyes.co/codigo_civil.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/codigo_civil.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?ruta=Codigo/30019754",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 84 de 1873",
    areasDelDerecho: ["Derecho Civil", "Contratos", "Obligaciones", "Familia"],
  },
  {
    codigo: "CODIGO_COMERCIO",
    nombre: "Codigo de Comercio",
    nombreCorto: "CCo",
    urlOficial: "http://leyes.co/codigo_de_comercio.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/codigo_comercio.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30019857",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 410 de 1971",
    areasDelDerecho: ["Derecho Comercial", "Sociedades", "Titulos Valores"],
  },

  // ==================== CODIGOS PENALES ====================
  {
    codigo: "CODIGO_PENAL",
    nombre: "Codigo Penal Colombiano",
    nombreCorto: "CP",
    urlOficial: "http://leyes.co/codigo_penal.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0599_2000.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1664159",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 599 de 2000",
    areasDelDerecho: ["Derecho Penal"],
  },
  {
    codigo: "CODIGO_PROCEDIMIENTO_PENAL",
    nombre: "Codigo de Procedimiento Penal",
    nombreCorto: "CPP",
    urlOficial: "http://leyes.co/codigo_de_procedimiento_penal.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0906_2004.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1668730",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 906 de 2004",
    areasDelDerecho: ["Derecho Penal", "Procedimiento Penal"],
  },
  {
    codigo: "CODIGO_PENAL_MILITAR",
    nombre: "Codigo Penal Militar",
    nombreCorto: "CPM",
    urlOficial: "http://leyes.co/codigo_penal_militar.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1407_2010.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1678951",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1407 de 2010",
    areasDelDerecho: ["Derecho Penal Militar", "Fuerzas Armadas"],
  },
  {
    codigo: "CODIGO_PENITENCIARIO",
    nombre: "Codigo Penitenciario y Carcelario",
    nombreCorto: "CPC",
    urlOficial: "http://leyes.co/codigo_penitenciario_y_carcelario.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0065_1993.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1657315",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 65 de 1993",
    areasDelDerecho: ["Derecho Penal", "Ejecucion Penal"],
  },

  // ==================== CODIGOS PROCESALES ====================
  {
    codigo: "CODIGO_GENERAL_PROCESO",
    nombre: "Codigo General del Proceso",
    nombreCorto: "CGP",
    urlOficial: "http://leyes.co/codigo_general_del_proceso.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1564_2012.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1683167",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1564 de 2012",
    areasDelDerecho: ["Derecho Procesal", "Derecho Civil"],
  },
  {
    codigo: "CODIGO_PROCEDIMIENTO_CIVIL",
    nombre: "Codigo de Procedimiento Civil (Derogado parcialmente)",
    nombreCorto: "CPC",
    urlOficial: "http://leyes.co/codigo_de_procedimiento_civil.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/codigo_procedimiento_civil.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?ruta=Codigo/30020348",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 1400 de 1970",
    areasDelDerecho: ["Derecho Procesal", "Derecho Civil"],
  },

  // ==================== CODIGOS LABORALES ====================
  {
    codigo: "CODIGO_SUSTANTIVO_TRABAJO",
    nombre: "Codigo Sustantivo del Trabajo",
    nombreCorto: "CST",
    urlOficial: "http://leyes.co/codigo_sustantivo_del_trabajo.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/codigo_sustantivo_trabajo.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30020046",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 2663 de 1950",
    areasDelDerecho: ["Derecho Laboral", "Contratos de Trabajo"],
  },
  {
    codigo: "CODIGO_PROCESAL_TRABAJO",
    nombre: "Codigo Procesal del Trabajo y Seguridad Social",
    nombreCorto: "CPTSS",
    urlOficial: "http://leyes.co/codigo_procesal_del_trabajo_y_de_la_seguridad_social.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/codigo_procesal_trabajo.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?ruta=Codigo/30019869",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 2158 de 1948 / Ley 2452 de 2025",
    areasDelDerecho: ["Derecho Laboral", "Seguridad Social"],
  },

  // ==================== CODIGOS ADMINISTRATIVOS ====================
  {
    codigo: "CPACA",
    nombre: "Codigo de Procedimiento Administrativo y de lo Contencioso Administrativo",
    nombreCorto: "CPACA",
    urlOficial: "http://leyes.co/codigo_de_procedimiento_administrativo_y_de_lo_contencioso_administrativo.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1437_2011.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1680117",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1437 de 2011",
    areasDelDerecho: ["Derecho Administrativo"],
  },
  {
    codigo: "CODIGO_CONTENCIOSO_ADMINISTRATIVO",
    nombre: "Codigo Contencioso Administrativo (Derogado)",
    nombreCorto: "CCA",
    urlOficial: "http://leyes.co/codigo_contencioso_administrativo.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/decreto_0001_1984.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1369066",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 01 de 1984",
    areasDelDerecho: ["Derecho Administrativo"],
  },
  {
    codigo: "CODIGO_REGIMEN_DEPARTAMENTAL",
    nombre: "Codigo de Regimen Departamental",
    nombreCorto: "CRD",
    urlOficial: "http://leyes.co/codigo_de_regimen_departamental.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/decreto_1222_1986.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30019886",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 1222 de 1986",
    areasDelDerecho: ["Derecho Administrativo", "Derecho Territorial"],
  },
  {
    codigo: "CODIGO_REGIMEN_MUNICIPAL",
    nombre: "Codigo de Regimen Municipal",
    nombreCorto: "CRM",
    urlOficial: "http://leyes.co/codigo_de_regimen_municipal.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/decreto_1333_1986.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30019887",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 1333 de 1986",
    areasDelDerecho: ["Derecho Administrativo", "Derecho Territorial"],
  },

  // ==================== CODIGOS DE FAMILIA Y MENORES ====================
  {
    codigo: "CODIGO_INFANCIA_ADOLESCENCIA",
    nombre: "Codigo de la Infancia y la Adolescencia",
    nombreCorto: "CIA",
    urlOficial: "http://leyes.co/codigo_de_la_infancia_y_la_adolescencia.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1098_2006.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1673639",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1098 de 2006",
    areasDelDerecho: ["Derecho de Familia", "Menores", "Derechos Humanos"],
  },
  {
    codigo: "CODIGO_MENOR",
    nombre: "Codigo del Menor (Derogado)",
    nombreCorto: "CM",
    urlOficial: "http://leyes.co/codigo_del_menor.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/decreto_2737_1989.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1376074",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 2737 de 1989",
    areasDelDerecho: ["Derecho de Familia", "Menores"],
  },

  // ==================== CODIGOS DISCIPLINARIOS ====================
  {
    codigo: "CODIGO_DISCIPLINARIO_UNICO",
    nombre: "Codigo Disciplinario Unico",
    nombreCorto: "CDU",
    urlOficial: "http://leyes.co/codigo_disciplinario_unico.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0734_2002.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1666017",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 734 de 2002",
    areasDelDerecho: ["Derecho Disciplinario", "Derecho Administrativo"],
  },
  {
    codigo: "CODIGO_GENERAL_DISCIPLINARIO",
    nombre: "Codigo General Disciplinario",
    nombreCorto: "CGD",
    urlOficial: "http://leyes.co/codigo_general_disciplinario.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1952_2019.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30036379",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1952 de 2019",
    areasDelDerecho: ["Derecho Disciplinario", "Derecho Administrativo"],
  },
  {
    codigo: "CODIGO_DISCIPLINARIO_ABOGADO",
    nombre: "Codigo Disciplinario del Abogado",
    nombreCorto: "CDA",
    urlOficial: "http://leyes.co/codigo_disciplinario_del_abogado.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1123_2007.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1674423",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1123 de 2007",
    areasDelDerecho: ["Derecho Disciplinario", "Etica Profesional"],
  },

  // ==================== CODIGOS DE POLICIA Y SEGURIDAD ====================
  {
    codigo: "CODIGO_NACIONAL_POLICIA",
    nombre: "Codigo Nacional de Policia y Convivencia",
    nombreCorto: "CNP",
    urlOficial: "http://leyes.co/codigo_nacional_de_policia.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1801_2016.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30021736",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1801 de 2016",
    areasDelDerecho: ["Derecho de Policia", "Convivencia"],
  },

  // ==================== CODIGOS ELECTORALES ====================
  {
    codigo: "CODIGO_ELECTORAL",
    nombre: "Codigo Electoral",
    nombreCorto: "CE",
    urlOficial: "http://leyes.co/codigo_electoral.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/decreto_2241_1986.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30019889",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 2241 de 1986",
    areasDelDerecho: ["Derecho Electoral", "Derecho Publico"],
  },

  // ==================== CODIGOS AMBIENTALES Y RECURSOS NATURALES ====================
  {
    codigo: "CODIGO_RECURSOS_NATURALES",
    nombre: "Codigo Nacional de Recursos Naturales Renovables y Proteccion al Medio Ambiente",
    nombreCorto: "CRNR",
    urlOficial: "http://leyes.co/codigo_nacional_de_recursos_naturales_renovables_y_de_proteccion_al_medio_ambiente.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/decreto_2811_1974.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1536871",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 2811 de 1974",
    areasDelDerecho: ["Derecho Ambiental", "Recursos Naturales"],
  },
  {
    codigo: "CODIGO_MINAS",
    nombre: "Codigo de Minas",
    nombreCorto: "CMi",
    urlOficial: "http://leyes.co/codigo_de_minas.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0685_2001.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1665217",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 685 de 2001",
    areasDelDerecho: ["Derecho Minero", "Derecho Ambiental"],
  },

  // ==================== CODIGOS DE TRANSPORTE ====================
  {
    codigo: "CODIGO_TRANSITO",
    nombre: "Codigo Nacional de Transito Terrestre",
    nombreCorto: "CNT",
    urlOficial: "http://leyes.co/codigo_nacional_de_transito_terrestre.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0769_2002.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1666376",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 769 de 2002",
    areasDelDerecho: ["Derecho de Transito", "Transporte"],
  },
  {
    codigo: "CODIGO_NAVEGACION_FLUVIAL",
    nombre: "Codigo Nacional de Navegacion y Actividades Portuarias Fluviales",
    nombreCorto: "CNAPF",
    urlOficial: "http://leyes.co/codigo_nacional_de_navegacion_y_actividades_portuarias_fluviales.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1242_2008.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1676414",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1242 de 2008",
    areasDelDerecho: ["Derecho Maritimo", "Transporte Fluvial"],
  },

  // ==================== CODIGOS SANITARIOS ====================
  {
    codigo: "CODIGO_SANITARIO",
    nombre: "Codigo Sanitario Nacional",
    nombreCorto: "CSN",
    urlOficial: "http://leyes.co/codigo_sanitario_nacional.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0009_1979.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1564714",
    tipo: "codigo",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 9 de 1979",
    areasDelDerecho: ["Derecho Sanitario", "Salud Publica"],
  },

  // ==================== ESTATUTOS ====================
  {
    codigo: "ESTATUTO_TRIBUTARIO",
    nombre: "Estatuto Tributario",
    nombreCorto: "ET",
    urlOficial: "http://leyes.co/estatuto_tributario.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30019885",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 624 de 1989",
    areasDelDerecho: ["Derecho Tributario", "Impuestos"],
  },
  {
    codigo: "ESTATUTO_CONSUMIDOR",
    nombre: "Estatuto del Consumidor",
    nombreCorto: "EC",
    urlOficial: "http://leyes.co/el_estatuto_del_consumidor.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1480_2011.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1681955",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1480 de 2011",
    areasDelDerecho: ["Derecho del Consumidor", "Proteccion al Consumidor"],
  },
  {
    codigo: "ESTATUTO_ARBITRAJE",
    nombre: "Estatuto de Arbitraje Nacional e Internacional",
    nombreCorto: "EAI",
    urlOficial: "http://leyes.co/estatuto_de_arbitraje_nacional_e_internacional.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1563_2012.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1683153",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1563 de 2012",
    areasDelDerecho: ["Derecho Arbitral", "Resolucion de Conflictos"],
  },
  {
    codigo: "ESTATUTO_ORGANICO_SISTEMA_FINANCIERO",
    nombre: "Estatuto Organico del Sistema Financiero",
    nombreCorto: "EOSF",
    urlOficial: "http://leyes.co/estatuto_organico_del_sistema_financiero.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_organico_sistema_financiero.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1448706",
    tipo: "codigo",
    entidadEmisora: "Gobierno Nacional",
    numeroNorma: "Decreto 663 de 1993",
    areasDelDerecho: ["Derecho Financiero", "Banca"],
  },
  {
    codigo: "ESTATUTO_REGISTRO_INSTRUMENTOS",
    nombre: "Estatuto de Registro de Instrumentos Publicos",
    nombreCorto: "ERIP",
    urlOficial: "http://leyes.co/estatuto_de_registro_de_instrumentos_publicos.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1579_2012.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1683513",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1579 de 2012",
    areasDelDerecho: ["Derecho Notarial", "Registro Publico"],
  },
  {
    codigo: "ESTATUTO_CIUDADANIA_JUVENIL",
    nombre: "Estatuto de Ciudadania Juvenil",
    nombreCorto: "ECJ",
    urlOficial: "http://leyes.co/se_expide_el_estatuto_de_ciudadania_juvenil.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1622_2013.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1684885",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1622 de 2013",
    areasDelDerecho: ["Derechos de la Juventud", "Participacion"],
  },
  {
    codigo: "ESTATUTO_MIGRATORIO",
    nombre: "Estatuto Migratorio Permanente",
    nombreCorto: "EMP",
    urlOficial: "http://leyes.co/estatuto_migratorio_permanente.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_2136_2021.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=30042170",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 2136 de 2021",
    areasDelDerecho: ["Derecho Migratorio", "Extranjeria"],
  },

  // ==================== LEYES ESPECIALES IMPORTANTES ====================
  {
    codigo: "LEY_HABEAS_DATA",
    nombre: "Ley de Habeas Data - Proteccion de Datos Personales",
    nombreCorto: "LHD",
    urlOficial: "http://leyes.co/ley_de_habeas_data.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1581_2012.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1683235",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1581 de 2012",
    areasDelDerecho: ["Proteccion de Datos", "Derechos Fundamentales"],
  },
  {
    codigo: "LEY_ACOSO_LABORAL",
    nombre: "Ley de Acoso Laboral",
    nombreCorto: "LAL",
    urlOficial: "http://leyes.co/acoso_laboral.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1010_2006.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1672069",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1010 de 2006",
    areasDelDerecho: ["Derecho Laboral", "Acoso Laboral"],
  },
  {
    codigo: "LEY_PROPIEDAD_HORIZONTAL",
    nombre: "Ley de Propiedad Horizontal",
    nombreCorto: "LPH",
    urlOficial: "http://leyes.co/propiedad_horizontal.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0675_2001.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1665129",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 675 de 2001",
    areasDelDerecho: ["Derecho Inmobiliario", "Propiedad Horizontal"],
  },
  {
    codigo: "LEY_VICTIMAS",
    nombre: "Ley de Victimas y Restitucion de Tierras",
    nombreCorto: "LVR",
    urlOficial: "http://leyes.co/victimas_y_restitucion_de_tierras.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1448_2011.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1680697",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1448 de 2011",
    areasDelDerecho: ["Derechos Humanos", "Justicia Transicional"],
  },
  {
    codigo: "LEY_INSOLVENCIA",
    nombre: "Regimen de Insolvencia Empresarial",
    nombreCorto: "RIE",
    urlOficial: "http://leyes.co/regimen_de_insolvencia_empresarial.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1116_2006.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1674296",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1116 de 2006",
    areasDelDerecho: ["Derecho Comercial", "Insolvencia"],
  },
  {
    codigo: "LEY_SOCIEDADES",
    nombre: "Ley de Sociedades por Acciones Simplificadas (SAS)",
    nombreCorto: "SAS",
    urlOficial: "http://leyes.co/sociedad_por_acciones_simplificada.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_1258_2008.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1676802",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 1258 de 2008",
    areasDelDerecho: ["Derecho Comercial", "Sociedades"],
  },

  // ==================== CODIGOS DE ETICA ====================
  {
    codigo: "CODIGO_ETICA_MEDICO",
    nombre: "Codigo de Etica Medica",
    nombreCorto: "CEM",
    urlOficial: "http://leyes.co/codigo_de_etica.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0023_1981.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1597286",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 23 de 1981",
    areasDelDerecho: ["Etica Medica", "Derecho de la Salud"],
  },
  {
    codigo: "CODIGO_DEONTOLOGICO_BIOETIC",
    nombre: "Codigo Deontologico y Bioetico de Enfermeria",
    nombreCorto: "CDB",
    urlOficial: "http://leyes.co/codigo_deontologico_y_bioetico.htm",
    urlSenado: "http://www.secretariasenado.gov.co/senado/basedoc/ley_0911_2004.html",
    urlSUIN: "https://www.suin-juriscol.gov.co/viewDocument.asp?id=1668818",
    tipo: "ley",
    entidadEmisora: "Congreso de la Republica",
    numeroNorma: "Ley 911 de 2004",
    areasDelDerecho: ["Etica Profesional", "Enfermeria"],
  },
];

// Departamentos de Colombia
export const DEPARTAMENTOS_COLOMBIA = [
  "Amazonas", "Antioquia", "Arauca", "Atlantico", "Bolivar", "Boyaca",
  "Caldas", "Caqueta", "Casanare", "Cauca", "Cesar", "Choco", "Cordoba",
  "Cundinamarca", "Guainia", "Guaviare", "Huila", "La Guajira", "Magdalena",
  "Meta", "Narino", "Norte de Santander", "Putumayo", "Quindio", "Risaralda",
  "San Andres y Providencia", "Santander", "Sucre", "Tolima", "Valle del Cauca",
  "Vaupes", "Vichada", "Bogota D.C."
];

// Areas del derecho
export const AREAS_DERECHO = [
  "Derecho Civil",
  "Derecho Penal",
  "Derecho Laboral",
  "Derecho Comercial",
  "Derecho Administrativo",
  "Derecho Constitucional",
  "Derecho de Familia",
  "Derecho Tributario",
  "Derecho Ambiental",
  "Derecho de Seguros",
  "Derecho Inmobiliario",
  "Derecho Migratorio",
  "Derecho Procesal",
  "Derecho Disciplinario",
  "Derecho Electoral",
  "Derecho de Policia",
  "Derecho Minero",
  "Derecho de Transito",
  "Derecho Maritimo",
  "Derecho Sanitario",
  "Derecho Financiero",
  "Derecho del Consumidor",
  "Derecho Arbitral",
  "Derecho Notarial",
  "Derechos Humanos",
  "Derecho Penal Militar",
  "Seguridad Social",
  "Propiedad Horizontal",
  "Etica Profesional",
  "Justicia Transicional",
];

// Fuentes oficiales de leyes colombianas
export const FUENTES_LEGALES = {
  SUIN_JURISCOL: {
    nombre: "SUIN-Juriscol",
    url: "https://www.suin-juriscol.gov.co/",
    descripcion: "Sistema Unico de Informacion Normativa - Ministerio de Justicia (+98,000 normas)",
  },
  SECRETARIA_SENADO: {
    nombre: "Secretaria del Senado",
    url: "http://www.secretariasenado.gov.co/senado/basedoc/",
    descripcion: "Base de datos de codigos y leyes actualizadas",
  },
  LEYES_CO: {
    nombre: "Leyes.co",
    url: "http://leyes.co/codigos.htm",
    descripcion: "Portal de legislacion colombiana con comentarios",
  },
  CORTE_CONSTITUCIONAL: {
    nombre: "Corte Constitucional",
    url: "https://www.corteconstitucional.gov.co/",
    descripcion: "Jurisprudencia constitucional",
  },
  RELATORIA_CC: {
    nombre: "Relatoria Corte Constitucional",
    url: "https://jurisprudencia.ramajudicial.gov.co/WebRelatoria/cc/index.xhtml",
    descripcion: "Sentencias C, T, SU, A",
  },
  RELATORIA_CSJ: {
    nombre: "Relatoria Corte Suprema de Justicia",
    url: "https://jurisprudencia.ramajudicial.gov.co/WebRelatoria/csj/index.html",
    descripcion: "Casaciones y Tutelas",
  },
  RELATORIA_CE: {
    nombre: "Relatoria Consejo de Estado",
    url: "https://jurisprudencia.ramajudicial.gov.co/WebRelatoria/ce/index.xhtml",
    descripcion: "Contencioso Administrativo",
  },
  DATOS_ABIERTOS: {
    nombre: "Datos Abiertos Colombia",
    url: "https://www.datos.gov.co/",
    descripcion: "API de datos abiertos del gobierno",
  },
};
